name: .NET Build
description: Standard dotnet CLI restore, build, and optional pack

inputs:
  configuration:
    description: 'Build configuration'
    required: false
    default: 'Release'
  src-folder:
    description: 'Folder containing the solution'
    required: false
    default: 'src'
  solution-file:
    description: 'Solution file relative to src-folder'
    required: false
    default: ''
  create-packages:
    description: 'Run dotnet pack after build'
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: NuGet Restore
      shell: bash
      run: dotnet restore ${{ inputs.solution-file }}
      working-directory: ${{ inputs.src-folder }}

    - name: Build
      shell: bash
      run: dotnet build --no-restore --configuration ${{ inputs.configuration }} ${{ inputs.solution-file }}
      working-directory: ${{ inputs.src-folder }}

    - name: Pack
      if: inputs.create-packages == 'true'
      shell: bash
      run: dotnet pack --no-restore --configuration ${{ inputs.configuration }} ${{ inputs.solution-file }} --m:1
      working-directory: ${{ inputs.src-folder }}
