name: Common publish to GitHub Packages workflow

permissions:
  packages: write

on:
  workflow_call:
    inputs:
      artifactName:
        type: string
        default: 'nuget-packages'
        description: 'Name of the artifact containing .nupkg files to publish'

jobs:
  publish-github-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Download packages
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          name: ${{ inputs.artifactName }}

      - name: Setup .NET Environment
        uses: reactiveui/actions-common/.github/actions/dotnet-environment@main
        with:
          stamp-version: 'false'

      - name: Push to GitHub Packages
        shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd "$RUNNER_TEMP" && dotnet run - <<'CS'
          using System.Diagnostics;
          using static System.Environment;

          if (Directory.GetFiles(GetEnvironmentVariable("GITHUB_WORKSPACE")!, "*.nupkg") is not [_, ..] packages)
          {
              Console.WriteLine("::error::The artifact holds no .nupkg files.");
              return 1;
          }

          var source = $"https://nuget.pkg.github.com/{GetEnvironmentVariable("GITHUB_REPOSITORY_OWNER")}/index.json";
          foreach (var package in packages.Order(StringComparer.Ordinal))
          {
              if (Process.Run("dotnet", ["nuget", "push", package, "--source", source, "--api-key", GetEnvironmentVariable("GITHUB_TOKEN")!, "--skip-duplicate"]) is { ExitCode: not 0 } push)
              {
                  return push.ExitCode;
              }
          }

          return 0;
          CS
